# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_joint_controller:
  ros__parameters:
    joints:
      - finger_left_joint
      - finger_right_joint
    # 核心补充：指令接口（位置控制）
    command_interfaces:
      - position
    # 核心补充：状态接口（反馈位置/速度）
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      finger_left_joint:
        trajectory: 0.05
        goal: 0.01
      finger_right_joint:
        trajectory: 0.05
        goal: 0.01

